apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # Must match the spec fields below with name field.
  name: my.mine.jp
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: mine.jp
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: my
    # singular name to be used as an alias on the CLI and for display
    singular: my
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: My